model_name: lsa
bow_corpus_file: tm_bow_corpus.mm
tfidf_corpus_file: tm_tfidf_corpus.mm
id2word_file: tm_bow_dict.dict
num_topics: 7
tfidf_model_file: tm_tfidf
model_file: tm_model
preprocess_type: tfidf
topic_map:
  '0': 'Others'
  '1': 'Healthy (Sugar and Gluten Free)'
  '2': 'Coffee and its complements'
  '3': 'Dog food and Prices'
  '4': 'Tea Time Snacks'
  '5': 'Beverages and Flavoured bars'
  '6': 'Chocolate, Coconut water, Sauces'